/**
 * Expo config plugin — Android build configuration that has to survive
 * `npx expo prebuild --clean`.
 *
 * - arm64-v8a only (halves the APK; see README → "Supported devices")
 * - R8 minification + resource shrinking in release
 * - Real release signing pulled from the environment, never the AOSP debug key
 * - Cleartext HTTP scoped to telematics.oasa.gr instead of every host
 * - Drops microphone / external-storage / overlay permissions that arrive
 *   transitively from expo-av and expo-file-system
 * - Foreground-service permissions + service type for react-native-background-actions
 * - Verifies the react-native-background-actions patch actually landed
 *
 * Every string match below fails the build loudly when it stops matching. The
 * previous version of this plugin silently skipped its node_modules patch on a
 * version bump, which turned into a runtime
 * `MissingForegroundServiceTypeException` on Android 14 with no build warning.
 */

const {
  AndroidConfig,
  withGradleProperties,
  withAndroidManifest,
  withAppBuildGradle,
  withDangerousMod,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/** The only host this app is allowed to reach over plaintext HTTP. */
const CLEARTEXT_HOST = 'telematics.oasa.gr';

const NETWORK_SECURITY_CONFIG_RES = '@xml/network_security_config';

/**
 * Permissions no bus tracker should ship.
 *
 * - RECORD_AUDIO / MODIFY_AUDIO_SETTINGS come from expo-av's autolinked config
 *   plugin. We only ever *play* audio (a silent keep-alive loop and the arrival
 *   chime in services/notifications.ts), and `Audio.setAudioModeAsync` there
 *   never sets `playThroughEarpieceAndroid`, which is the one option that would
 *   need MODIFY_AUDIO_SETTINGS. A microphone request is a Play-review flag.
 * - READ/WRITE_EXTERNAL_STORAGE come from expo-file-system's library manifest.
 *   Everything we write lives in cacheDirectory/documentDirectory and the APK
 *   is handed to the installer through a FileProvider content:// URI, none of
 *   which touches shared storage.
 * - SYSTEM_ALERT_WINDOW is a debug-tooling permission. The RN template's
 *   `src/debug/AndroidManifest.xml` re-declares it at higher merge priority, so
 *   dev builds keep it and only release loses it.
 */
const BLOCKED_PERMISSIONS = [
  'android.permission.RECORD_AUDIO',
  'android.permission.MODIFY_AUDIO_SETTINGS',
  'android.permission.READ_EXTERNAL_STORAGE',
  'android.permission.WRITE_EXTERNAL_STORAGE',
  'android.permission.SYSTEM_ALERT_WINDOW',
];

const BG_ACTIONS_SOURCE =
  'node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/RNBackgroundActionsTask.java';

/* ── Network security config ──────────────────────────────────── */

const RELEASE_NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by plugins/withAndroidOptimizations.js — do not edit by hand.

  The app used to set android:usesCleartextTraffic="true" on <application>,
  which permits plaintext to every host on the internet. api.ts talks HTTPS
  first and only fails over to HTTP for OASA's telematics endpoint, so that one
  domain is the only exception we need.
-->
<network-security-config>
  <base-config cleartextTrafficPermitted="false">
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </base-config>
  <domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="false">${CLEARTEXT_HOST}</domain>
  </domain-config>
</network-security-config>
`;

const DEBUG_NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by plugins/withAndroidOptimizations.js — do not edit by hand.

  Debug-only override (src/debug/res beats src/main/res for the debug variant).
  Metro, the dev menu and LAN reloads all speak plain HTTP, so the debug build
  keeps the permissive policy the release build must not have.
-->
<network-security-config>
  <base-config cleartextTrafficPermitted="true">
    <trust-anchors>
      <certificates src="system" />
      <certificates src="user" />
    </trust-anchors>
  </base-config>
</network-security-config>
`;

/* ── Gradle: release signing ──────────────────────────────────── */

const SIGNING_PREAMBLE = `
/**
 * Release signing material comes from the environment so that no keystore and
 * no password is ever committed. CI decodes the KEYSTORE_BASE64 secret to a
 * file and exports OASA_KEYSTORE_PATH — see README → "Release signing".
 *
 * The AOSP debug keystore that ships inside every copy of React Native is
 * public (CN=Android Debug, password "android"). Signing a published APK with
 * it means anyone can build a signature-compatible "update", so it is fine for
 * assembleDebug and never acceptable for a release. Hence the hard failure.
 */
def oasaKeystoreFile = file(System.getenv('OASA_KEYSTORE_PATH') ?: 'oasa-release.keystore')
def oasaStorePassword = System.getenv('OASA_KEYSTORE_PASSWORD')
def oasaKeyAlias = System.getenv('OASA_KEY_ALIAS')
def oasaKeyPassword = System.getenv('OASA_KEY_PASSWORD')
def oasaHasReleaseSigning = oasaKeystoreFile.exists() && oasaStorePassword && oasaKeyAlias && oasaKeyPassword

if (!oasaHasReleaseSigning) {
    gradle.taskGraph.whenReady { graph ->
        if (graph.hasTask(':app:packageRelease')) {
            throw new GradleException(
                "Release signing is not configured.\\n" +
                "Set OASA_KEYSTORE_PATH (default: android/app/oasa-release.keystore), " +
                "OASA_KEYSTORE_PASSWORD, OASA_KEY_ALIAS and OASA_KEY_PASSWORD.\\n" +
                "See README > 'Release signing'. Refusing to fall back to the public AOSP debug key."
            )
        }
    }
}

`;

const RELEASE_SIGNING_CONFIG = `        if (oasaHasReleaseSigning) {
            release {
                storeFile oasaKeystoreFile
                storePassword oasaStorePassword
                keyAlias oasaKeyAlias
                keyPassword oasaKeyPassword
                // minSdk is 24, so v1 (JAR) signing buys nothing and only slows
                // installs. v3 is the important one: it carries a rotation
                // proof, so this key can be replaced later WITHOUT forcing
                // another uninstall/reinstall. Having just put users through
                // one signature migration, it is worth never repeating it.
                enableV1Signing false
                enableV2Signing true
                enableV3Signing true
            }
        }
`;

/** Throw with enough context that whoever bumps Expo can fix it in one pass. */
function assertMatched(matched, what) {
  if (!matched) {
    throw new Error(
      `[withAndroidOptimizations] could not ${what}. The generated Android ` +
        'project no longer matches what this plugin expects — most likely an ' +
        'Expo/React Native template change. Update plugins/withAndroidOptimizations.js.',
    );
  }
}

function withAndroidOptimizations(config) {
  // ─── Gradle properties: ABI split + R8 ──────────────────────
  config = withGradleProperties(config, (cfg) => {
    const props = cfg.modResults;
    const set = (key, value) => {
      const existing = props.find((p) => p.type === 'property' && p.key === key);
      if (existing) existing.value = value;
      else props.push({ type: 'property', key, value });
    };
    // arm64 only. Every Android phone sold since ~2017 is arm64, but this does
    // mean the APK will not install on armeabi-v7a or on an x86_64 emulator.
    set('reactNativeArchitectures', 'arm64-v8a');
    set('android.enableMinifyInReleaseBuilds', 'true');
    set('android.enableShrinkResourcesInReleaseBuilds', 'true');
    return cfg;
  });

  // ─── Strip transitively-added permissions ───────────────────
  // `android.blockedPermissions` in app.config.ts is the declarative form, but
  // nothing in the SDK 54 prebuild pipeline reads it — the plugin that would is
  // exported and never called. Applying it here is what actually makes it work.
  config = AndroidConfig.Permissions.withBlockedPermissions(config, BLOCKED_PERMISSIONS);

  // ─── AndroidManifest: TLS policy + foreground service ────────
  config = withAndroidManifest(config, (cfg) => {
    cfg.modResults = AndroidConfig.Manifest.ensureToolsAvailable(cfg.modResults);
    const manifest = cfg.modResults.manifest;

    const app = manifest.application?.[0];
    assertMatched(app, 'find the <application> node in AndroidManifest.xml');

    // Scope plaintext to one domain via res/xml/network_security_config.xml
    // instead of opening every host. The attribute below is ignored once a
    // network security config is present, so it is removed rather than kept.
    delete app.$['android:usesCleartextTraffic'];
    app.$['android:networkSecurityConfig'] = NETWORK_SECURITY_CONFIG_RES;

    // Android 14 refuses to start a foreground service without a declared type.
    if (!app.service) app.service = [];
    const bgService = app.service.find(
      (s) => s.$['android:name'] === 'com.asterinet.react.bgactions.RNBackgroundActionsTask',
    );
    if (bgService) {
      bgService.$['android:foregroundServiceType'] = 'mediaPlayback';
    } else {
      app.service.push({
        $: {
          'android:name': 'com.asterinet.react.bgactions.RNBackgroundActionsTask',
          'android:foregroundServiceType': 'mediaPlayback',
        },
      });
    }

    // Add foreground service permissions
    if (!manifest['uses-permission']) manifest['uses-permission'] = [];
    const perms = manifest['uses-permission'];
    const addPerm = (name) => {
      if (!perms.find((p) => p.$['android:name'] === name)) {
        perms.push({ $: { 'android:name': name } });
      }
    };
    addPerm('android.permission.FOREGROUND_SERVICE');
    addPerm('android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK');
    addPerm('android.permission.WAKE_LOCK');

    return cfg;
  });

  // ─── app/build.gradle: real release signing ──────────────────
  config = withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        '[withAndroidOptimizations] expected a Groovy app/build.gradle; ' +
          `got "${cfg.modResults.language}".`,
      );
    }
    let contents = cfg.modResults.contents;

    // Idempotent: prebuild --clean regenerates the file, but a plain prebuild
    // reuses it and would otherwise stack the block up on every run.
    if (!contents.includes('oasaHasReleaseSigning')) {
      const androidBlock = /\nandroid\s*\{/;
      assertMatched(androidBlock.test(contents), 'find the `android {` block in app/build.gradle');
      contents = contents.replace(androidBlock, `${SIGNING_PREAMBLE}android {`);

      const signingConfigs = /(signingConfigs\s*\{\n)/;
      assertMatched(
        signingConfigs.test(contents),
        'find the `signingConfigs {` block in app/build.gradle',
      );
      contents = contents.replace(signingConfigs, `$1${RELEASE_SIGNING_CONFIG}`);

      // Drop the template's "generate your own keystore" note — it is exactly
      // what the block above does, and leaving it there reads as still-TODO.
      // Optional: the wording is RN's, not ours, and may change.
      contents = contents.replace(
        /[ \t]*\/\/ Caution! In production, you need to generate your own keystore file\.\n[ \t]*\/\/ see https:\/\/reactnative\.dev\/docs\/signed-apk-android\.\n/,
        '',
      );

      // The debug build type sets `signingConfig signingConfigs.debug` too, so
      // anchor on the first occurrence *after* `release {` inside `buildTypes`.
      const releaseSigning = /(buildTypes\s*\{[\s\S]*?\brelease\s*\{[\s\S]*?)signingConfig\s+signingConfigs\.debug/;
      assertMatched(
        releaseSigning.test(contents),
        'find the release build type\'s signing config in app/build.gradle',
      );
      contents = contents.replace(
        releaseSigning,
        '$1signingConfig oasaHasReleaseSigning ? signingConfigs.release : null',
      );
    }

    cfg.modResults.contents = contents;
    return cfg;
  });

  // ─── Generated resources + patch verification ─────────────────
  config = withDangerousMod(config, [
    'android',
    (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const androidRoot = cfg.modRequest.platformProjectRoot;

      const writeXml = (relativePath, body) => {
        const target = path.join(androidRoot, relativePath);
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.writeFileSync(target, body, 'utf8');
      };
      writeXml('app/src/main/res/xml/network_security_config.xml', RELEASE_NETWORK_SECURITY_CONFIG);
      writeXml('app/src/debug/res/xml/network_security_config.xml', DEBUG_NETWORK_SECURITY_CONFIG);

      // react-native-background-actions is patched by patch-package (see
      // patches/) rather than rewritten here — one mechanism for the whole
      // repo, and it does not leave node_modules in a mutated state. All this
      // does is refuse to build if the patch stopped applying, because the
      // symptom otherwise is a crash on a user's Android 14 phone.
      const bgActionsFile = path.resolve(projectRoot, BG_ACTIONS_SOURCE);
      if (fs.existsSync(bgActionsFile)) {
        const source = fs.readFileSync(bgActionsFile, 'utf8');
        if (!source.includes('FOREGROUND_SERVICE_TYPE_MEDIA_PLAYBACK')) {
          throw new Error(
            '[withAndroidOptimizations] react-native-background-actions is not patched: ' +
              `${BG_ACTIONS_SOURCE} does not call startForeground() with a service type. ` +
              'Run `npx patch-package react-native-background-actions` after re-applying ' +
              'the fix, or check that `npm ci` ran the patch-package postinstall. ' +
              'Without it the arrival-alert service crashes on Android 14 ' +
              '(MissingForegroundServiceTypeException).',
          );
        }
      }

      return cfg;
    },
  ]);

  return config;
}

module.exports = withAndroidOptimizations;
