import { StyleSheet } from 'react-native';
import { colors, spacing, radius, font } from '../../theme';

export const s = StyleSheet.create({
  panel: {
    flex: 1,
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    marginTop: -radius.xl,
    paddingTop: spacing.xs,
    paddingHorizontal: spacing.md,
    borderTopWidth: 1,
    borderColor: colors.border,
  },
  panelHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
    alignSelf: 'center',
    marginBottom: spacing.sm,
  },
  instructionWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
  },
  instructionText: {
    color: colors.textMuted,
    fontSize: font.size.sm,
    textAlign: 'center',
    lineHeight: 20,
  },
  loadingWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.sm,
  },
  loadingText: {
    color: colors.textMuted,
    fontSize: font.size.sm,
  },
  resultScroll: {
    flex: 1,
    paddingBottom: spacing.xl,
  },
  resultCard: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  legRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: spacing.xs,
  },
  legWalkText: {
    color: '#4285F4',
    fontSize: font.size.xs,
    fontWeight: '600',
    flex: 1,
  },
  legTransferText: {
    color: colors.textMuted,
    fontSize: font.size.xs,
    fontWeight: '600',
    flex: 1,
  },
  legBoardText: {
    color: colors.text,
    fontSize: font.size.xs,
    fontWeight: '600',
    flex: 1,
  },
  legDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: spacing.xs,
    paddingLeft: spacing.lg,
  },
  legDetailText: {
    color: colors.text,
    fontSize: font.size.xs,
    flex: 1,
  },
  legDetailMuted: {
    color: colors.textMuted,
    fontSize: font.size.xs,
    flex: 1,
  },
  lineBadge: {
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 1,
    minWidth: 36,
    alignItems: 'center',
  },
  lineBadgeText: {
    color: '#FFFFFF',
    fontSize: font.size.xs,
    fontWeight: '700',
  },
  waitBadge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 1,
    borderRadius: radius.sm,
  },
  waitBadgeText: {
    color: '#000',
    fontSize: font.size.xs,
    fontWeight: '700',
  },
  waitUnknownText: {
    color: colors.textMuted,
    fontSize: font.size.xs,
    fontWeight: '600',
  },
  totalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.xs,
    paddingTop: spacing.xs,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  totalText: {
    color: colors.text,
    fontSize: font.size.md,
    fontWeight: '700',
  },
  etaText: {
    color: colors.textMuted,
    fontSize: font.size.xs,
    marginTop: 2,
  },
  navBtn: {
    padding: spacing.xs,
  },
  stopPin: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stopPinInner: {
    width: 4,
    height: 6,
    borderRadius: 1,
    backgroundColor: '#FFF',
  },
  stopPinLarge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stopPinLargeText: {
    color: '#FFF',
    fontSize: 11,
    fontWeight: '800',
  },
  offlineTitle: {
    color: colors.text,
    fontSize: font.size.lg,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: spacing.md,
  },
  offlineSubtitle: {
    color: colors.textMuted,
    fontSize: font.size.sm,
    textAlign: 'center',
    marginTop: spacing.xs,
    lineHeight: 20,
  },
  offlineBtn: {
    marginTop: spacing.lg,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm + 2,
  },
  offlineBtnText: {
    fontSize: font.size.md,
    fontWeight: '700',
  },
  tagBadge: {
    alignSelf: 'flex-start',
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 1,
    marginBottom: spacing.xs,
  },
  tagBadgeText: {
    color: '#FFF',
    fontSize: font.size.xs - 1,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
});
